### ISSUE TITLE
Auto sync with github actions workflow?

### ISSUE THREAD

**Issue by benthecoder** [MrShoopa/Canvas-2-GTasks#2]
Hi! I love your code, it's really clean and tested well. I was wondering if you thought about adding an auto-syncing feature to this code so that it runs on a cron job? This way you won't have to run the code each time to get an update on google task.

**Comment by cooltacocodes** [comment]
Hey @benthecoder! Thanks for checking this out, didn't think it'd be used by others! :)

Thanks for the great idea, I'll take a look at this now given this was made by a lesser experienced me!
